language:
  java

jdk:
  oraclejdk8

cache:
  directories:
    -$HOME/.m2

sudo:
  false

install:
  true

script:
  - mvn test
  - mvn cobertura:cobertura

after_success:
  - bash <(curl -s https://codecov.io/bash) -t 4384913e-5f1e-4efa-af09-6c8a00c345ec